name: Bug report
description: バグ報告
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: 概要
      description: 何が起きている？
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: 再現手順
      description: 例）1. ... 2. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 期待する結果
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: 実際の結果
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: 環境
      description: OS / 言語 / バージョンなど
